name: Ontology Documentation CI

on: [push]

jobs:

  ontdoc:
    uses: sparqlunicorn/sparqlunicornGoesGIS-ontdoc/.github/workflows/udoc.yml@main
    with: 
        version: v017
        rdffilepath: rdf/atlantgis_small.ttl rdf/atlantgis.owl
        docpath: docs
        prefixns: http://atlantgis.squirrel.link/data/
        prefixnsshort: atlantgis
        indexpages: true
        createcollections: true
        preferredlang: en
        ghpages: true
        metadatatable: true
        createnonNSPages: true
        ogcapifeatures: true
        gh-pages-folder: docs/ontdoc/ 

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Create Ontology Documentation 🔧
      run: |
         sudo apt-get install python3 python3-setuptools -y
         sudo apt-get install gcc libpq-dev -y
         sudo apt-get install python-dev -y
         sudo apt-get install python3-dev python3-pip python3-venv python3-wheel -y
         sudo pip3 install wheel pylode
         mkdir docs
         cd docs
         pylode -i ../linkeddata/ontology/atlantgis.owl -o index
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         BRANCH: gh-pages
         FOLDER: docs/
