name: Ontology Documentation CI

on: [push]

jobs:

  ontdoc:
    uses: sparqlunicorn/sparqlunicornGoesGIS-ontdoc/.github/workflows/udoc.yml@main
    with: 
        version: v017
        rdffilepath: linkeddata/rdf/atlantgis_small.ttl linkeddata/ontology/atlantgis.owl
        docpath: docs
        prefixns: http://atlantgis.squirrel.link/data/
        prefixnsshort: atlantgis
        indexpages: true
        createcollections: true
        preferredlang: en
        ghpages: true
        metadatatable: true
        createnonNSPages: true
        ogcapifeatures: true
        ghpagesfolder: ontdoc/ 

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Create Ontology Documentation 🔧
      run: |
         sudo apt-get install python3 python3-setuptools -y
         sudo apt-get install gcc libpq-dev -y
         sudo apt-get install python3-dev python3-pip python3-venv python3-wheel -y
         sudo pip3 install wheel pylode==2.13.2
         mkdir docs
         cd docs
         mkdir ontology/
         cd ontology
         pylode -i ../../linkeddata/ontology/atlantgis.owl -o index
    - name: Convert Markdown to HTML
      uses: natescherer/markdown-to-html-with-github-style-action@v1
      with:
           path: data.md
           outputpath: docs/index.html  
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         BRANCH: gh-pages
         FOLDER: docs/
