name: Ontology Documentation CI

on: [push]

jobs:

  ontdoc:
    uses: sparqlunicorn/sparqlunicornGoesGIS-ontdoc/.github/workflows/udoc.yml@main
    with: 
        version: v017
        rdffilepath: linkeddata/rdf/atlantgis_small.ttl linkeddata/ontology/atlantgis.owl
        docpath: docs
        prefixns: http://situx.github.io/AtlantGIS/data/
        prefixnsshort: atlantgis
        indexpages: true
        createcollections: true
        preferredlang: en
        createVOWL: true
        ghpages: true
        metadatatable: true
        createnonNSPages: true
        ogcapifeatures: true
        ghpagesfolder: data/ 

  build:
    needs: ontdoc
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Create Ontology Documentation 🔧
      run: |
         sudo apt-get install python3 python3-setuptools -y
         sudo apt-get install gcc libpq-dev -y
         sudo apt-get install python3-dev python3-pip python3-venv python3-wheel -y
         sudo pip3 install wheel pylode==2.13.2
         mkdir docs
         cd docs
         mkdir ontology/
         cd ontology
         pylode -i ../../linkeddata/ontology/atlantgis.owl -o index
    - name: Converts Markdown to HTML
      uses: jaywcjlove/markdown-to-html-cli@main
      with:
         source: data.md
         output: docs/index.html
         github-corners: https://github.com/jaywcjlove/markdown-to-html-cli
         favicon: data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🌐</text></svg>
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         BRANCH: gh-pages
         FOLDER: docs/
         
